vich_uploader:
    db_driver: orm

    mappings:
        cv_file:
            uri_prefix: /fichiers/cv
            upload_destination: "%kernel.project_dir%/public/fichiers/cv"
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
